version: '2'
linters:
  default: none
  enable:
    - errcheck
    - gocritic
    - goprintffuncname
    - staticcheck
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - unused

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - lll
      - text: "weak cryptography"
        linters:
          - gosec

formatters:
  enable:
    - gofmt
    - goimports
